using TestItems

@testitem "oracle fixture normalization" begin
    using Test

    include(joinpath(dirname(@__DIR__), "data", "fixtures", "generate_oracle_fixture.jl"))

    rows = Dict{String, String}[
    Dict(
        "Motif1" => "[RKQ]L[IV]T",
        "Motif2" => "AR[KR]L[IV]",
        "Sim1" => "Degenerate Overlap",
        "Sim2" => "Variant Overlap",
        "Match" => "[kqr]L[IV]",
        "MatchPos" => "3",
        "MatchIC" => "2.402",
        "NormIC" => "0.706",
        "CoreIC" => "0.947",
        "Score" => "2.118",
        "Info1" => "3.40",
        "Info2" => "4.54"
    ),
    Dict(
        "Motif1" => "[RKQ]L[IV]T",
        "Motif2" => "[KR]L[IMV]",
        "Sim1" => "Complex Parent",
        "Sim2" => "Complex Subsequence",
        "Match" => "[kqr]L[imv]",
        "MatchPos" => "3",
        "MatchIC" => "2.267",
        "NormIC" => "0.944",
        "CoreIC" => "0.893",
        "Score" => "2.831",
        "Info1" => "3.40",
        "Info2" => "2.40"
    ),
    Dict(
        "Motif1" => "[RKQ]L[IV]T",
        "Motif2" => "A[KR]L[IMV]",
        "Sim1" => "Complex Overlap",
        "Sim2" => "Complex Overlap",
        "Match" => "[kqr]L[imv]",
        "MatchPos" => "3",
        "MatchIC" => "2.267",
        "NormIC" => "0.666",
        "CoreIC" => "0.893",
        "Score" => "1.999",
        "Info1" => "3.40",
        "Info2" => "3.40"
    )
]

    normalize_rows(rows)
    @test [row["Motif2"] for row in rows] == [
        "AR[KR]L[IV]",
        "A[KR]L[IMV]",
        "[KR]L[IMV]"
    ]

    mktempdir() do tmpdir
        output = joinpath(tmpdir, "normalized.tsv")
        write_normalized(output, rows)
        lines = readlines(output)

        @test lines[1] == "# Generated by data/fixtures/generate_oracle_fixture.jl"
        @test startswith(lines[2], "# Date: ")
        @test lines[3] == "# Source: CompariMotif oracle (black-box)"
        @test lines[4] == join(ORACLE_NORMALIZED_COLUMNS, '\t')
        @test lines[5:end] == [
            "[RKQ]L[IV]T\tAR[KR]L[IV]\tDegenerate Overlap\tVariant Overlap\t[kqr]L[IV]\t3\t2.402\t0.706\t0.947\t2.118\t3.40\t4.54",
            "[RKQ]L[IV]T\tA[KR]L[IMV]\tComplex Overlap\tComplex Overlap\t[kqr]L[imv]\t3\t2.267\t0.666\t0.893\t1.999\t3.40\t3.40",
            "[RKQ]L[IV]T\t[KR]L[IMV]\tComplex Parent\tComplex Subsequence\t[kqr]L[imv]\t3\t2.267\t0.944\t0.893\t2.831\t3.40\t2.40"
        ]
    end
end

@testitem "oracle path resolution" begin
    using Test

    include(joinpath(dirname(@__DIR__), "data", "fixtures", "generate_oracle_fixture.jl"))

    @test resolve_oracle_path(Dict("SLiMSuite_PATH" => "/tmp/SLiMSuite")) ==
          joinpath("/tmp/SLiMSuite", ORACLE_RELATIVE_PATH)

    @test_throws ErrorException resolve_oracle_path(Dict{String, String}())
end
